In [2]:
# Step 1: Load real-world data

import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

# Read dataset
df = pd.read_csv('student_marks1.csv')

# Show data
df

Saving student_marks1.csv to student_marks1.csv


,Student,Math,Physics,Chemistry,English,CS,Biology,Economics,Statistics
0,S1,78,72.0,75.0,80.0,85,70.0,68.0,74
1,S2,65,60.0,58.0,70.0,75,62.0,55.0,60
2,S3,90,88.0,NaN,92.0,95,89.0,84.0,87
3,S4,50,55.0,52.0,60.0,65,58.0,50.0,54
4,S5,82,78.0,NaN,85.0,88,NaN,72.0,79
5,S6,70,68.0,65.0,72.0,78,66.0,64.0,69
6,S7,92,90.0,88.0,NaN,96,91.0,89.0,90
7,S8,55,58.0,60.0,62.0,68,57.0,53.0,59
8,S9,76,74.0,72.0,78.0,82,70.0,69.0,73
9,S10,88,NaN,83.0,90.0,92,86.0,82.0,84


In [3]:
# Step 2: Convert data into matrix form

# Remove non-numeric column
data = df.drop(columns=['Student'])

# Convert to numpy matrix
A = data.to_numpy()

print("Matrix A:")
print(A)

Matrix A:
[[78. 72. 75. 80. 85. 70. 68. 74.]
 [65. 60. 58. 70. 75. 62. 55. 60.]
 [90. 88. nan 92. 95. 89. 84. 87.]
 [50. 55. 52. 60. 65. 58. 50. 54.]
 [82. 78. nan 85. 88. nan 72. 79.]
 [70. 68. 65. 72. 78. 66. 64. 69.]
 [92. 90. 88. nan 96. 91. 89. 90.]
 [55. 58. 60. 62. 68. 57. 53. 59.]
 [76. 74. 72. 78. 82. 70. 69. 73.]
 [88. nan 83. 90. 92. 86. 82. 84.]
 [60. 62. 58. 65. 70. 61. 59. 63.]
 [95. 93. 91. 96. 98. 94. 90. 92.]
 [68. 66. 64. 70. 75. 65. 62. 67.]
 [80. 78. 76. 82. 85. 77. 74. 79.]
 [72. 70. 68. 75. 80. nan 66. 71.]
 [85. 82. 80. 88. 90. 83. 79. 81.]
 [58. 55. 53. 60. 65. 57. 52. 56.]
 [91. 89. 87. 93. 95. 90. nan 89.]
 [75. 73. 70. 78. 82. 71. 69. 74.]
 [66. 64. 62. 68. 72. 63. 60. 65.]]


In [4]:
# Step 3: Matrix simplification using RREF

from sympy import Matrix

M = Matrix(np.nan_to_num(A))  # replace NaN for computation
rref_matrix, pivots = M.rref()

print("RREF Matrix:")
print(rref_matrix)

RREF Matrix:
Matrix([[1, 0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]])


In [5]:
# Step 4: Analyze vector space

rank = np.linalg.matrix_rank(np.nan_to_num(A))
nullity = A.shape[1] - rank

print("Rank:", rank)
print("Nullity:", nullity)

Rank: 8
Nullity: 0


In [6]:
# Step 5: Remove redundant features

# We approximate this using rank info
print("Number of independent features:", rank)

Number of independent features: 8


In [7]:
# Step 6: Orthogonalization using QR decomposition

Q, R = np.linalg.qr(np.nan_to_num(A))

print("Orthogonal basis (Q):")
print(Q)

Orthogonal basis (Q):
[[-0.22978377 -0.01334897  0.0963603  -0.06399904  0.03139513  0.0216989
   0.04527658  0.31715451]
 [-0.19148648 -0.01112414  0.03876504 -0.08555541 -0.23713663 -0.05391729
  -0.0833118   0.71542504]
 [-0.26513512 -0.07440275 -0.68325838  0.00274697  0.01878243 -0.44838794
   0.0519775  -0.04996382]
 [-0.14729729 -0.11457282  0.10572565 -0.14574289 -0.56469111 -0.14434879
  -0.08011323 -0.12197814]
 [-0.24156756 -0.04168983 -0.62443125 -0.00869379 -0.07894797  0.47879544
  -0.07065889 -0.02156392]
 [-0.20621621 -0.05254241  0.06814078 -0.06010259 -0.07280226 -0.03084933
   0.04454766  0.02712976]
 [-0.27102702 -0.07658878  0.11384127  0.94649631 -0.1007146  -0.00694402
  -0.00987348 -0.01031586]
 [-0.16202702 -0.09606912  0.13995325 -0.11750221 -0.41853158 -0.060458
  -0.04510588 -0.26844978]
 [-0.22389188 -0.05910051  0.08731731 -0.06478647  0.09642558 -0.00263373
   0.10977617  0.14678853]
 [-0.25924323  0.95844106  0.02267535 -0.00826027 -0.0600272  -0.0279687

In [8]:
# Step 7: Projection of a subject's scores

b = np.nan_to_num(A[:, 0])  # first subject's scores

projection = Q @ Q.T @ b

print("Projection of first subject's scores:")
print(projection)

Projection of first subject's scores:
[78. 65. 90. 50. 82. 70. 92. 55. 76. 88. 60. 95. 68. 80. 72. 85. 58. 91.
 75. 66.]


In [9]:
# Step 8: Predict missing values using Least Squares

A_original = data.to_numpy()
A_filled = A_original.copy()

rows, cols = A_original.shape

for col in range(cols):

    missing_rows = np.isnan(A_original[:, col])

    if np.sum(missing_rows) == 0:
        continue

    b = A_original[:, col]
    A_reduced = np.delete(A_original, col, axis=1)

    valid_rows = ~np.isnan(b)

    A_train = A_reduced[valid_rows]
    b_train = b[valid_rows]

    A_train = np.nan_to_num(A_train)

    x = np.linalg.lstsq(A_train, b_train, rcond=None)[0]

    A_test = A_reduced[missing_rows]
    A_test = np.nan_to_num(A_test)

    predictions = A_test @ x

    A_filled[missing_rows, col] = predictions

    print(f"\nPredictions for {data.columns[col]}:")
    for idx, val in zip(np.where(missing_rows)[0], predictions):
        print(f"Student {idx+1}: {val:.2f}")


Predictions for Physics:
Student 10: 83.87

Predictions for Chemistry:
Student 3: 84.69
Student 5: 75.93

Predictions for English:
Student 7: 92.86

Predictions for Biology:
Student 5: 81.19
Student 15: 70.30

Predictions for Economics:
Student 18: 85.43


In [10]:
# Step 9: Pattern discovery using eigenvalues

cov_matrix = np.cov(np.nan_to_num(A).T)

eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:")
print(eigenvalues)

Eigenvalues:
[1019.20947206  614.7278681   123.53864315    1.19396462    1.90987251
  281.16902204  383.54068362  446.86310547]


In [11]:
# Step 10: Diagonalization

D = np.diag(eigenvalues)

print("Diagonal Matrix D:")
print(D)

print("Eigenvector Matrix:")
print(eigenvectors)

Diagonal Matrix D:
[[1019.20947206    0.            0.            0.            0.
     0.            0.            0.        ]
 [   0.          614.7278681     0.            0.            0.
     0.            0.            0.        ]
 [   0.            0.          123.53864315    0.            0.
     0.            0.            0.        ]
 [   0.            0.            0.            1.19396462    0.
     0.            0.            0.        ]
 [   0.            0.            0.            0.            1.90987251
     0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
   281.16902204    0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.          383.54068362    0.        ]
 [   0.            0.            0.            0.            0.
     0.            0.          446.86310547]]
Eigenvector Matrix:
[[ 2.54183366e-01  3.47354090e-01  4.32273430e-01 -5.66346915e-01
   5.18059190e

In [12]:
# Step 11: Final output

print("Final Completed Matrix (with predicted values):")
print(A_filled)

Final Completed Matrix (with predicted values):
[[78.         72.         75.         80.         85.         70.
  68.         74.        ]
 [65.         60.         58.         70.         75.         62.
  55.         60.        ]
 [90.         88.         84.68686774 92.         95.         89.
  84.         87.        ]
 [50.         55.         52.         60.         65.         58.
  50.         54.        ]
 [82.         78.         75.92598457 85.         88.         81.1876757
  72.         79.        ]
 [70.         68.         65.         72.         78.         66.
  64.         69.        ]
 [92.         90.         88.         92.86210202 96.         91.
  89.         90.        ]
 [55.         58.         60.         62.         68.         57.
  53.         59.        ]
 [76.         74.         72.         78.         82.         70.
  69.         73.        ]
 [88.         83.87045079 83.         90.         92.         86.
  82.         84.        ]
 [60.         6